## We're gonna save our models using both pickle and joblib  
p.s. joblib should be used when the program has many numpy arrays and it is also easier to code

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
data = pd.read_csv('C:\\Users\\Ahmar Hussain\\Desktop\\Datasets\\homeprices.csv')
data

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000
5  4100  810000

In [28]:
model = linear_model.LinearRegression()
model.fit(data[['area']], data.price)

LinearRegression()

In [29]:
model.coef_, model.intercept_

(array([167.30954677]), 76692.3818707813)

In [30]:
model.predict([[5000]])

c:\Users\Ahmar Hussain\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

we're gonna save the model to use later using pickle library

In [15]:
import pickle

In [16]:
with open('model_pickle','wb') as f:     # wb for write binary
    pickle.dump(model,f)

In [17]:
with open('model_pickle','rb') as f:     # rb for read binary
    mp = pickle.load(f)

In [19]:
del model

In [20]:
model

NameError: name 'model' is not defined

In [21]:
mp.predict([[5000]])

c:\Users\Ahmar Hussain\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

gives the same prediction as before

### Now we'll use joblib

In [26]:
import joblib as jb

In [31]:
jb.dump(model,'model_joblib')

['model_joblib']

In [32]:
mj = jb.load('model_joblib')     # it returns the model object

In [34]:
mj.predict([[5000]])

c:\Users\Ahmar Hussain\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])